channels:
  - conda-forge
dependencies:
  - python=3.12.11
  - numpy=2.3.3
  - click=8.3.0
  - gdal=3.10.3
  - geopandas=1.1.1
  - rasterio=1.4.3
  - affine=2.4.0
  - spectral=0.24
  - netcdf4=1.7.2
  - tqdm=4.67.1
